const exampleTheme = {
    ltr: "ltr",
    rtl: "rtl",
    placeholder: "__global-editor-placeholder",
    paragraph: "__global-editor-paragraph",
    quote: "__global-editor-quote",
    heading: {
        h1: "__global-editor-heading-h1",
        h2: "__global-editor-heading-h2",
        h3: "__global-editor-heading-h3",
        h4: "__global-editor-heading-h4",
        h5: "__global-editor-heading-h5",
    },
    list: {
        nested: {
            listitem: "__global-editor-nested-listitem",
        },
        ol: "__global-editor-list-ol",
        ul: "__global-editor-list-ul",
        listitem: "__global-editor-listitem",
    },
    image: "__global-editor-image",
    link: "__global-editor-link",
    text: {
        bold: "__global-editor-text-bold",
        italic: "__global-editor-text-italic",
        overflowed: "__global-editor-text-overflowed",
        hashtag: "__global-editor-text-hashtag",
        underline: "__global-editor-text-underline",
        strikethrough: "__global-editor-text-strikethrough",
        underlineStrikethrough: "__global-editor-text-underlineStrikethrough",
        code: "__global-editor-text-code",
    },
    code: "__global-editor-code",
    codeHighlight: {
        atrule: "__global-editor-tokenAttr",
        attr: "__global-editor-tokenAttr",
        boolean: "__global-editor-tokenProperty",
        builtin: "__global-editor-tokenSelector",
        cdata: "__global-editor-tokenComment",
        char: "__global-editor-tokenSelector",
        class: "__global-editor-tokenFunction",
        "class-name": "__global-editor-tokenFunction",
        comment: "__global-editor-tokenComment",
        constant: "__global-editor-tokenProperty",
        deleted: "__global-editor-tokenProperty",
        doctype: "__global-editor-tokenComment",
        entity: "__global-editor-tokenOperator",
        function: "__global-editor-tokenFunction",
        important: "__global-editor-tokenVariable",
        inserted: "__global-editor-tokenSelector",
        keyword: "__global-editor-tokenAttr",
        namespace: "__global-editor-tokenVariable",
        number: "__global-editor-tokenProperty",
        operator: "__global-editor-tokenOperator",
        prolog: "__global-editor-tokenComment",
        property: "__global-editor-tokenProperty",
        punctuation: "__global-editor-tokenPunctuation",
        regex: "__global-editor-tokenVariable",
        selector: "__global-editor-tokenSelector",
        string: "__global-editor-tokenSelector",
        symbol: "__global-editor-tokenProperty",
        tag: "__global-editor-tokenProperty",
        url: "__global-editor-tokenOperator",
        variable: "__global-editor-tokenVariable",
    },
}

export default exampleTheme
